name: toomeedom
favicon: null
layout_spectrum: 0.5468704907689244
typography_spectrum: 0.0073311952874064445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9879326615482569
  lightness: 0.4523624142166227
  saturation: 0.2873986600898206
  rhythmicContrast: 0.49456847785040736
purpose: []
