name: toomeedom
favicon: null
layout_spectrum: 0.5468704907689244
typography_spectrum: 0.0073311952874064445
title: Lowell Testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#fefefe'
    - '#2b2f20'
    - '#50525f'
    - '#d3d3d3'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
